version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  hello-world:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Print Hello World
          command: echo "Hello, World!"
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - hello-world
