version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo apt-get update && sudo apt-get install -y your-dependencies
      - run:
          name: Build Project
          command: make build
      - run:
          name: Run Tests
          command: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
